name: 'stripe-mock'
description: 'Starts stripe-mock'

inputs:
  base:
    description: 'Base branch'
    required: true
    default: github.base_ref || github.ref_name

runs:
  using: "composite"
  steps:
    - name: Start stripe-mock
      shell: bash
      run: |
        BETA_ARG=""

        if [ "${{inputs.base.contains('b')}}" == "true" ]; then
          BETA_ARG="-beta"
        fi

        docker run -d -p 12111-12112:12111-12112 stripe/stripe-mock $BETA_ARG && sleep 5

