name: 'stripe-mock'
description: 'Starts stripe-mock'

inputs:
  base:
    description: 'Base branch'
    required: true
    default: "${{ github.base_ref || github.ref_name }}"
  fixtures:
    description: 'Path to custom fixtures file'
    required: false
  spec_path:
    description: 'Path to OpenAPI specification'
    required: false

runs:
  using: "composite"
  steps:
    - name: Start stripe-mock
      shell: bash
      run: |
        BETA_ARG=""
        FIXTURES_ARG=""
        SPEC_PATH_ARG=""

        if [ "${{ contains(inputs.base, 'b') }}" == "true" ]; then
          BETA_ARG="-beta"
        fi

        if [ -n "${{ inputs.fixtures }}" ]; then
          FIXTURES_ARG="-fixtures ${{ inputs.fixtures }}"
        fi

        if [ -n "${{ inputs.spec_path }}" ]; then
          SPEC_PATH_ARG="-spec ${{ inputs.spec_path }}"
        fi

        docker run -d -p 12111-12112:12111-12112 \
          -v "${{ github.workspace }}:/workspace" \
          stripe/stripe-mock $BETA_ARG $FIXTURES_ARG $SPEC_PATH_ARG && sleep 5
